### ISSUE TITLE
Add Dark and Light Mode

### ISSUE THREAD

**Issue by Lohithsurya** [acmpesuecc/Compiler#2]
The current pages doesn't have any dark mode, add the dark mode and make it switch between light and dark

**Comment by RithishRM** [comment]
I want the issue

**Comment by QWERTY-Ak** [comment]
i want this issue

**Comment by Viprakshi** [comment]
can you assign me this?

**Comment by Lohithsurya** [comment]
!assign @RithishRM

**Comment by Lohithsurya** [comment]
@RithishRM the default time is 30mins show me the progress i will extend the time (show before the time runs out)

**Comment by RithishRM** [comment]
Going for dinner and will take some more time

**Comment by RithishRM** [comment]
Fixed the Issue

**Comment by Lohithsurya** [comment]
@RithishRM  its giving "react-scripts" error giving you 15 mins to solve it or will assign to someone else

**Comment by Lohithsurya** [comment]
!deassign

**Comment by Lohithsurya** [comment]
!assign @RithishRM 15

**Comment by RithishRM** [comment]
Its working for me without error
Try npm install and then npm start

**Comment by Shresht-Ahuja** [comment]
can i get assigned the issue plspls
